IRRM/Models/Incident.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Incident()
        {
            this.Incident_People_T = new HashSet<Incident_People_T>();
            this.RiskRegisters = new HashSet<RiskRegister>();
        }
    
        public int IncidentID { get; set; }
        public Nullable<int> EventTypeID { get; set; }
        public string IncidentNo { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public bool OnBehalfReporting { get; set; }
        public string ReporterName { get; set; }
        public string ReporterEmail { get; set; }
        public string ReporterDesignation { get; set; }
        public string ReporterBranch { get; set; }
        public string ReporterPhone { get; set; }
        public Nullable<System.DateTime> IncidentDate { get; set; }
        public string Description { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> IncidentTypeID { get; set; }
        public Nullable<int> IncidentSubTypeID { get; set; }
        public bool Confidential { get; set; }
        public string InvestigationComments { get; set; }
        public string InvestigatorReport { get; set; }
        public string InvestigationConclusion { get; set; }
        public Nullable<int> IncidentFeedbackTypeID { get; set; }
        public string FeedbackComments { get; set; }
        public Nullable<System.Guid> IncidentGUID { get; set; }
        public bool Registered { get; set; }
        public Nullable<System.DateTime> RegisteredOn { get; set; }
        public Nullable<System.DateTime> IncidentCreatedDate { get; set; }
        public string Outcome { get; set; }
        public string RemedialAction { get; set; }
        public Nullable<int> IncidentStatusID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public bool CreatorCanComment { get; set; }
        public Nullable<int> HarmScoreID { get; set; }
        public string RootCauseAnalysis { get; set; }
        public bool RiskAnalysisRequired { get; set; }
        public Nullable<bool> RiskAnalysisCompleted { get; set; }
        public Nullable<bool> ReOpened { get; set; }
        public string ReOpenRemarks { get; set; }
        public Nullable<int> FeedbackTypeID { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> InvestigationDueDate { get; set; }
    
        public virtual Branch_M Branch_M { get; set; }
        public virtual EventType_SM EventType_SM { get; set; }
        public virtual IncidentFeedbackType_M IncidentFeedbackType_M { get; set; }
        public virtual IncidentHarmScore_M IncidentHarmScore_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident_People_T> Incident_People_T { get; set; }
        public virtual IncidentPriorities_M IncidentPriorities_M { get; set; }
        public virtual IncidentStatus_M IncidentStatus_M { get; set; }
        public virtual Location_M Location_M { get; set; }
        public virtual Users_M Users_M { get; set; }
        public virtual IncidentSubTypes_M IncidentSubTypes_M { get; set; }
        public virtual IncidentTypes_M IncidentTypes_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskRegister> RiskRegisters { get; set; }
    }
}

IRRM/Controllers/IncidentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IRRM.Models;
using System.Text;
using System.IO;

namespace IRRM.Controllers
{
    public class IncidentsController : Controller
    {
        private IRRMEntities db = new IRRMEntities();
        private Utility utl = new Utility();
        // GET: Incidents
        public ActionResult Index()
        {
            if (Session["UserID"] == null) { return RedirectToAction("../Login"); }

            int UserID = Convert.ToInt32(Session["UserID"]);




            if (Convert.ToInt32(Session["RoleID"]) == 1)
            { // admin

                ViewBag.Incidents = db.Database.SqlQuery<_Incidents>(@"select distinct row_number() over(order by inc.IncidentID) as rownumber,inc.IncidentID,inc.InvestigationDueDate,inc.CreatedUserID,incCreated.Name as IncCreatedBy,incCreated.UserRoleID,IncidentNo,inc.IncidentTypeID,intype.IncidentType,
inc.IncidentSubTypeID,instype.IncidentSubType,inc.CreatorCanComment,
inc.BranchID,b.Branch,inc.LocationID,l.Location,IncidentDate,RegisteredOn,IncidentCreatedDate,inc.IncidentStatusID,inst.IncidentStatus,inpu.Name as AssignedTo,ip.Name as AssignedBy from  [dbo].[Incidents] inc
left join (
select incidentid,ipx.userid,incidentrelationid,asgnby.name from [Incident-People_T] ipx
left join Users_M asgnby on asgnby.UserID = ipx.CreateUserID
where IncidentRelationID=1
)ip on ip.IncidentID= inc.IncidentID
left join Users_M inpu on inpu.UserID = ip.UserID
left join Users_M incCreated on incCreated.UserID = inc.CreatedUserID
left join IncidentTypes_M intype on intype.IncidentTypeID = inc.IncidentTypeID
left join IncidentSubTypes_M instype on instype.IncidentSubTypeID = inc.IncidentSubTypeID
left join Branch_M b on b.BranchID = inc.BranchID
left join Location_M l on l.LocationID = inc.LocationID
left join IncidentStatus_M inst on inst.IncidentStatusID= inc.IncidentStatusID where inc.EventTypeID is not null and inc.IncidentStatusID is not null  and inc.IncidentStatusID<>6  order by inc.IncidentID desc").ToList();


            }
            else
            {
               List<_Incidents> inci  = db.Database.SqlQuery<_Incidents>(@"select distinct row_number() over(order by inc.IncidentID) as rownumber,inc.IncidentID,ip2.incidentrelationid,ip2.UserID as relationuserid, inc.InvestigationDueDate,inc.CreatedUserID,incCreated.Name as IncCreatedBy,incCreated.UserRoleID,IncidentNo,inc.IncidentTypeID,intype.IncidentType,inc.IncidentSubTypeID,instype.IncidentSubType,inc.CreatorCanComment,
inc.BranchID,b.Branch,inc.LocationID,l.Location,IncidentDate,RegisteredOn,IncidentCreatedDate,inc.IncidentStatusID,inst.IncidentStatus,inpu.Name as AssignedTo,ip.Name as AssignedBy from  [dbo].[Incidents] inc
left join (
select incidentid,ipx.userid,asgnby.name from [Incident-People_T] ipx
left join Users_M asgnby on asgnby.UserID = ipx.CreateUserID
where IncidentRelationID=1
)ip on ip.IncidentID= inc.IncidentID
left join (
select  ipx.userid,ipx.IncidentID,incidentrelationid  from [Incident-People_T] ipx
where IncidentRelationID<=2 or IncidentRelationID=7
)ip2 on ip2.IncidentID= inc.IncidentID
left join Users_M inpu on inpu.UserID = ip.UserID
left join Users_M incCreated on incCreated.UserID = inc.CreatedUserID
left join IncidentTypes_M intype on intype.IncidentTypeID = inc.IncidentTypeID
left join IncidentSubTypes_M instype on instype.IncidentSubTypeID = inc.IncidentSubTypeID
left join Branch_M b on b.BranchID = inc.BranchID
left join Location_M l on l.LocationID = inc.LocationID
left join IncidentStatus_M inst on inst.IncidentStatusID= inc.IncidentStatusID
where inc.Registered=1  and ((inc.CreatedUserID=" + UserID + ") or ip2.UserID=" + UserID + "  )   and inc.EventTypeID is not null  order by inc.IncidentID desc").ToList();


                List<_Incidents> distindidentids = (from incis in inci
                                                    group incis by incis.IncidentID into incigroup
                                                    select new _Incidents
                                                    {
                                                        rownumber = incigroup.Min(x => x.rownumber),
                                                    }).ToList();
                List<long> idsonly = distindidentids.Select(x => x.rownumber).ToList();

                ViewBag.Incidents = (from incidentsx in inci
                                    where idsonly.Contains(incidentsx.rownumber)
                                    select incidentsx).ToList();
            }
            //where inc.Registered=1  and ((inc.CreatedUserID=" + UserID + " and (CreatorCanComment=1 or inc.IncidentStatusID=6)) or ip2.UserID=" + UserID + "  )   and inc.EventTypeID is not null  order by inc.IncidentID desc").ToList();


            

            return View();
        }




        [HttpPost]
        public ActionResult Search(FormCollection col)
        {
            if (Session["UserID"] == null) { return RedirectToAction("../Login"); }

            int UserID = Convert.ToInt32(Session["UserID"]);


            string searchconditions = "";

            if (Convert.ToInt32(col["EventTypeID"]) != 0) {
                searchconditions += " and EventTypeID=" + Convert.ToInt32(col["EventTypeID"]) + " ";
            }
            if (Convert.ToString(col["IncidentDateFrom"]) != "")
            {
                searchconditions += " and RegisteredOn>='" + Convert.ToDateTime(col["IncidentDateFrom"]).ToString("yyyy-MM-dd") + " 00:00:00' ";
            }
            if (Convert.ToString(col["IncidentDateTo"]) != "")
            {
                searchconditions += " and RegisteredOn<='" + Convert.ToDateTime(col["IncidentDateTo"]).ToString("yyyy-MM-dd") + " 23:59:59' ";
            }
            if (Convert.ToInt32(col["IncidentTypeID"]) != 0)
            {
                searchconditions += " and inc.IncidentTypeID=" + Convert.ToInt32(col["IncidentTypeID"]) + " ";
            }
            if (Convert.ToInt32(col["IncidentSubTypeID"]) != 0)
            {
                searchconditions += " and inc.IncidentSubTypeID=" + Convert.ToInt32(col["IncidentSubTypeID"]) + " ";
            }
            if (Convert.ToInt32(col["StatusID"]) != 0)
            {
                searchconditions += " and inc.IncidentStatusID=" + Convert.ToInt32(col["StatusID"]) + " ";
            }
            if (Convert.ToInt32(col["MainRootCauseID"]) != 0)
            {
                searchconditions += " and inc.IncidentID in (select IncidentID from  [dbo].[Incidents_MainRootCause_T] where IncidentMainRootCauseID=" + Convert.ToInt32(col["MainRootCauseID"]) + ") ";
            }
            if (Convert.ToInt32(col["SubRootCauseID"]) != 0)
            {
                searchconditions += " and inc.IncidentID in (select IncidentID from  [dbo].[Incidents_MainRootCause_T] where IncidentMainRootCauseID in (select IncidentMainRootCauseID from   [dbo].[IncidentSubRootCause_M] where IncidentSubRootCauseID=" + Convert.ToInt32(col["SubRootCauseID"]) + ")) ";
            }



            if (Convert.ToInt32(col["IncidentPeopleInvolved"]) != 0)
            {
                searchconditions += " and inc.IncidentId in (select IncidentID from   [dbo].[Incident-People_T] where IncidentPeopleInvolvedID = " + Convert.ToInt32(col["IncidentPeopleInvolved"]) + ") ";
            }

            if (Convert.ToInt32(col["PriorityID"]) != 0)
            {
                searchconditions += " and inc.PriorityID=" + Convert.ToInt32(col["PriorityID"]) + " ";
            }
            if (Convert.ToInt32(col["HarmScoreID"]) != 0)
            {
                searchconditions += " and inc.HarmScoreID=" + Convert.ToInt32(col["HarmScoreID"]) + " ";
            }

            if (Convert.ToInt32(col["FeedbackTypeID"]) != 0)
            {
                searchconditions += " and inc.FeedbackTypeID=" + Convert.ToString(col["FeedbackTypeID"]) + " ";
            }
            if (Convert.ToInt32(col["LocationID"]) != 0)
            {
                searchconditions += " and inc.LocationID=" + Convert.ToString(col["LocationID"]) + " ";
            }




            if (Convert.ToInt32(Session["RoleID"]) == 1)
            { // admin

                string query = @"select distinct row_number() over(order by inc.IncidentID) as rownumber,inc.IncidentID, inc.InvestigationDueDate,inc.CreatedUserID,incCreated.Name as IncCreatedBy,incCreated.UserRoleID,IncidentNo,inc.IncidentTypeID,intype.IncidentType,inc.IncidentSubTypeID,instype.IncidentSubType,inc.CreatorCanComment,
inc.BranchID,b.Branch,inc.LocationID,l.Location,IncidentDate,RegisteredOn,IncidentCreatedDate,inc.IncidentStatusID,inst.IncidentStatus,inpu.Name as AssignedTo,ip.Name as AssignedBy from  [dbo].[Incidents] inc
left join (
select incidentid,ipx.userid,incidentrelationid,asgnby.name from [Incident-People_T] ipx
left join Users_M asgnby on asgnby.UserID = ipx.CreateUserID
where IncidentRelationID=1
)ip on ip.IncidentID= inc.IncidentID
left join Users_M inpu on inpu.UserID = ip.UserID
left join Users_M incCreated on incCreated.UserID = inc.CreatedUserID
left join IncidentTypes_M intype on intype.IncidentTypeID = inc.IncidentTypeID
left join IncidentSubTypes_M instype on instype.IncidentSubTypeID = inc.IncidentSubTypeID
left join Branch_M b on b.BranchID = inc.BranchID
left join Location_M l on l.LocationID = inc.LocationID
left join IncidentStatus_M inst on inst.IncidentStatusID= inc.IncidentStatusID where inc.IncidentStatusID is not null  " + searchconditions + " order by inc.RegisteredOn desc, inc.IncidentNo desc";

                ViewBag.Incidents = db.Database.SqlQuery<_Incidents>(query).ToList();


            }
            else
            {

IRRM/Views/Incidents/Delete.cshtml
@model IRRM.Models.Incident

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Incident</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IncidentNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncidentNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OnBehalfReporting)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OnBehalfReporting)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReporterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReporterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReporterEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReporterEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReporterDesignation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReporterDesignation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReporterBranch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReporterBranch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReporterPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReporterPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IncidentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncidentDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActionTaken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActionTaken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Confidential)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Confidential)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvestigationComments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvestigationComments)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvestigatorReport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvestigatorReport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FeedbackComments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FeedbackComments)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IncidentGUID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncidentGUID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Registered)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Registered)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisteredOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisteredOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IncidentCreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncidentCreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventSubType_T.EventSubtype)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventSubType_T.EventSubtype)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventType_T.Prefix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventType_T.Prefix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IncidentFeedbackType_M.IncidentFeedbackType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncidentFeedbackType_M.IncidentFeedbackType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IncidentStatus_M.IncidentStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncidentStatus_M.IncidentStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IncidentSubTypes_M.IncidentSubType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncidentSubTypes_M.IncidentSubType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IncidentTypes_M.IncidentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncidentTypes_M.IncidentType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location_M.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location_M.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Users_M.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Users_M.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Branch_M.Branch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Branch_M.Branch)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IRRM/Views/Incidents/HistoryReport.cshtml
@{
    ViewBag.Title = "History Report";
    Layout = null;
}

 @foreach (var x in ViewBag.HistoryIncidents)
 {
    <span>
        @Html.Raw(x.PageContent)
    </span>
 }

IRRM/Views/Incidents/SearchPartial.cshtml
@using (Html.BeginForm("Search", "Incidents"))
{
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-body">

                    <div class="col-md-2">
                        <div class="control-label "><b>Event Type  </b></div>
                        
                        <select name="EventTypeID" class="form-control">
                            <option value="0">Select-all</option>
                            @foreach (var et in ViewBag.EventTypeID)
                            {
                                <option @(et.EventTypeID == Convert.ToInt32(Request["EventTypeID"]) ? "selected" : "") value="@et.EventTypeID">@et.EventType</option>
                            }
                        </select>

                    </div>

                    <div class="col-md-2">
                        <div class="control-label"><b>Incident Date From  </b></div>
                        <input type="date" name="IncidentDateFrom" class="form-control" value="@Request["IncidentDateFrom"]" />
                    </div>
                    <div class="col-md-2">
                        <div class="control-label"><b>Incident Date To  </b></div>
                        <input type="date" name="IncidentDateTo" class="form-control"  value="@Request["IncidentDateTo"]"/>
                    </div>

                    <div class="col-md-2">
                        <div class="control-label"><b>Incident Type</b></div>
                        <select id="IncidentTypeID" name="IncidentTypeID" class="form-control" onchange="getincidentsubtypes()">
                            <option value="0">Select</option>
                            @foreach (var itp in ViewBag.IncidentTypeID)
                            {
                                <option @(itp.IncidentTypeID == Convert.ToInt32(Request["IncidentTypeID"]) ? "selected" : "")  value="@itp.IncidentTypeID">@itp.IncidentType</option>
                            }
                        </select>
                    </div>
                    <div class="col-md-2">
                        <div class="control-label"><b>Incident Sub Type</b></div>
                        <select name="IncidentSubTypeID" id="IncidentSubTypeID" class="form-control">
                            <option value="0">Select</option>
                        </select>
                    </div>
                    <div class="col-md-2">
                        <div class="control-label"><b>Status</b></div>
                        <select name="StatusID" id="StatusID" class="form-control">
                            <option value="0">Select</option>
                            @foreach (var itp in ViewBag.StatusID)
                            {
                                <option @(itp.IncidentStatusID == Convert.ToInt32(Request["StatusID"]) ? "selected" : "")   value="@itp.IncidentStatusID">@itp.IncidentStatus</option>
                            }
                        </select>

                    </div>
                    <br style="clear:both" />
                    <br style="clear:both" />
                    <div class="col-md-2">
                        <div class="control-label"><b>Main Root Cause</b></div>
                        <select name="MainRootCauseID" id="MainRootCauseID" class="form-control">
                            <option value="0">Select</option>
                            @foreach (var itp in ViewBag.IncidentRootCause)
                            {
                                <option @(itp.IncidentMainRootCauseID == Convert.ToInt32(Request["MainRootCauseID"]) ? "selected" : "")    value="@itp.IncidentMainRootCauseID">@itp.IncidentMainRootCause</option>
                            }
                        </select>

                    </div>

                    <div class="col-md-2">
                        <div class="control-label"><b>Sub Root Cause</b></div>
                        <select name="SubRootCauseID" id="SubRootCauseID" class="form-control">
                            <option value="0">Select</option>
                            @foreach (var itp in ViewBag.IncidentSubRootCause)
                            {
                                <option  @(itp.IncidentSubRootCauseID == Convert.ToInt32(Request["SubRootCauseID"]) ? "selected" : "")   value="@itp.IncidentSubRootCauseID">@itp.IncidentSubRootCause</option>
                            }

                        </select>

                    </div>

                    <div class="col-md-2">
                        <div class="control-label"><b>People Involved</b></div>
                        <select name="IncidentPeopleInvolved" id="IncidentPeopleInvolved" class="form-control">
                            <option value="0">Select</option>
                            @foreach (var itp in ViewBag.IncidentPeopleInvolved)
                            {
                                <option @(itp.IncidentPeopleInvolvedID == Convert.ToInt32(Request["IncidentPeopleInvolved"]) ? "selected" : "")    value="@itp.IncidentPeopleInvolvedID">@itp.IncidentPeopleInvolved</option>
                            }
                        </select>

                    </div>

                    <div class="col-md-2">
                        <div class="control-label"><b>Priority</b></div>
                        <select name="PriorityID" id="PriorityID" class="form-control">
                            <option value="0">Select</option>

                            @foreach (var itp in ViewBag.IncidentPriority)
                            {
                                <option  @(itp.IncidentPriorityID == Convert.ToInt32(Request["PriorityID"]) ? "selected" : "")  value="@itp.IncidentPriorityID">@itp.Priority</option>
                            }
                        </select>

                    </div>
                    <div class="col-md-2">
                        <div class="control-label"><b>Harm Score</b></div>
                        <select name="HarmScoreID" id="HarmScoreID" class="form-control">
                            <option value="0">Select</option>
                            @foreach (var itp in ViewBag.IncidentHarmScore)
                            {
                                <option @(itp.IncidentHarmScoreID == Convert.ToInt32(Request["HarmScoreID"]) ? "selected" : "") value="@itp.IncidentHarmScoreID">@itp.IncidentHarmScore</option>
                            }
                        </select>

                    </div>



                    <div class="col-md-2">
                        <div class="control-label"><b>Feedback</b></div>
                        <select name="FeedbackTypeID" id="FeedbackTypeID" class="form-control">
                            <option value="0">Select</option>
                            @foreach (var itp in ViewBag.FeedbackTypeID)
                            {
                                <option @(itp.IncidentFeedbackTypeID == Convert.ToInt32(Request["FeedbackTypeID"]) ? "selected" : "")  value="@itp.IncidentFeedbackTypeID">@itp.IncidentFeedbackType</option>
                            }
                        </select>
                    </div>

                    <div class="col-md-12"> </div>
                        <div class="control-label"><b>&nbsp;&nbsp;</b></div>
                        <div class="col-md-1">
                            <input type="submit" class="btn btn-danger" value="SEARCH" />
                        </div>
                        <div class="col-md-2">
                            <a class="btn btn-warning" href="@Url.Content("~/Incidents")">CLEAR</a>
                        </div>
                   

                </div>
            </div>
        </div>
    </div>

}

IRRM/Views/Incidents/Success.cshtml
<style>
    .form-control {
        width: 100%;
    }
</style>


<div class="content-page">
    <!-- Start content -->
    <div class="content">

        <div class="container">

            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-body">
                            <h2 class="col-md-6">Report Incident</h2>
                            
                        </div>

                    </div>
                </div>
            </div>
 



            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-body">
                            <div class="col-md-12">
                               
                                <br />
                                <b>Thank you for reporting the event. Your report will be registered after reviewing the details.</b>
                                <br />
                                <br />
                                <br />
                                <br />
                                <br />
                                <br />
                                <br />
                                <br />
                                <br />
                                <br /><br />
<br />
<br />
<br />
<br /><br />
<br />
<br />
<br />
<br /><br />
<br />
<br />
<br />
<br />
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>




      


    </div>
</div>

 